# Generated by Django 4.1.7 on 2023-06-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosInstituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_instituicao', models.CharField(max_length=100, verbose_name='Nome_Instituição')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('rua', models.CharField(max_length=100, verbose_name='Rua')),
                ('num', models.IntegerField(verbose_name='Número')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('complemento', models.CharField(max_length=100, verbose_name='Complemento')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('tel', models.CharField(max_length=25, verbose_name='Telefone')),
                ('cel', models.CharField(max_length=25, verbose_name='Celular')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('senha', models.CharField(max_length=100, verbose_name='Senha')),
                ('descricao', models.CharField(max_length=250, verbose_name='Descricao')),
                ('forma_ajuda1', models.CharField(max_length=150, verbose_name='Forma_doacao1')),
                ('forma_ajuda2', models.CharField(max_length=150, verbose_name='Forma_doacao2')),
                ('forma_ajuda3', models.CharField(max_length=150, verbose_name='Forma_doacao3')),
                ('latitude', models.CharField(max_length=100, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=100, verbose_name='Longitude')),
                ('data_hora_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data_Hora_Cadastro')),
            ],
        ),
        migrations.CreateModel(
            name='DadosUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=100, verbose_name='Nome_Usuário')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('rua', models.CharField(max_length=100, verbose_name='Rua')),
                ('num', models.IntegerField(verbose_name='Número')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('data_hora_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data_Hora_Cadastro')),
            ],
        ),
    ]
