# Generated by Django 4.1.7 on 2023-04-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_instituicao', models.CharField(max_length=100, verbose_name='Nome_Instituição')),
                ('cnpj', models.IntegerField(verbose_name='CNPJ')),
                ('cep', models.IntegerField(verbose_name='CEP')),
                ('rua', models.CharField(max_length=100, verbose_name='Rua')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('complemento', models.CharField(max_length=100, verbose_name='Complemento')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('data_hora_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data_Hora_Cadastro')),
            ],
        ),
    ]
